name: "Setup FFmpeg + PG client and wait"
description: "Install FFmpeg and Postgres client (Linux) and wait for pg_isready"
inputs:
  host:
    description: "Postgres host"
    required: false
    default: "127.0.0.1"
  port:
    description: "Postgres port"
    required: true
  user:
    description: "Postgres user"
    required: true
  install-portaudio:
    description: "Install portaudio (Linux)"
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Install FFmpeg + PG client (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg postgresql-client ${PORTAUDIO:-}
      env:
        PORTAUDIO: ${{ inputs.install-portaudio == 'true' && 'portaudio19-dev' || '' }}

    - name: Wait for Postgres
      shell: bash
      run: |
        host='${{ inputs.host }}'
        port='${{ inputs.port }}'
        user='${{ inputs.user }}'
        echo "Waiting for Postgres at ${host}:${port} as ${user}"
        for i in {1..60}; do
          if pg_isready -h "$host" -p "$port" -U "$user"; then
            echo "Postgres is ready"; exit 0; fi;
          echo "Attempt $i: waiting for Postgres..."; sleep 2;
        done
        echo "Postgres did not become ready in time" >&2; exit 1
